version: '2'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    tty: true    
    environment:
      PGID: <pgid>
      PUID: <ugid>
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - <path to data>:/config 
      - <path to downloads>:/downloads 
      - <path to watch folder>:/watch 