version: '2'

services:
  samba:
    image: dperson/samba
    container_name: samba-server
    hostname: <your server name>
    environment:
      - WORKGROUP=WORKGROUP
      - PGID=<pgid>
      - PUID=<ugid>
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - <your path to share>:/media/<folder-name>:z
    command: '-u "<user>;<password>" -s "<folder-name>;/media/<folder-name>;yes;no;no;<user>" -S'