version: '2'

services:
  noip:
    image: coppit/no-ip
    container_name: noip  
    restart: always
    tty: true
    environment:
      PGID: <pgid>
      PUID: <ugid>
    volumes:
      - /etc/localtime:/etc/localtime
      - <your config path>:/config